version: "3"

services:

  runtime-setup:
    image: swift-nio:16.04-5.2
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.2"

  unit-tests:
    image: swift-nio:16.04-5.2

  integration-tests:
    image: swift-nio:16.04-5.2

  test:
    image: swift-nio:16.04-5.2
    environment:
      - MAX_ALLOCS_ALLOWED_1000_addHandlers=47050
      - MAX_ALLOCS_ALLOWED_1000_addHandlers_sync=40050
      - MAX_ALLOCS_ALLOWED_1000_autoReadGetAndSet=32050
      - MAX_ALLOCS_ALLOWED_1000_autoReadGetAndSet_sync=50
      - MAX_ALLOCS_ALLOWED_1000_getHandlers=12050
      - MAX_ALLOCS_ALLOWED_1000_getHandlers_sync=50
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=30540
      - MAX_ALLOCS_ALLOWED_1000_tcpbootstraps=4100
      - MAX_ALLOCS_ALLOWED_1000_tcpconnections=178010
      - MAX_ALLOCS_ALLOWED_1000_udp_reqs=16050
      - MAX_ALLOCS_ALLOWED_1000_udpbootstraps=2000
      - MAX_ALLOCS_ALLOWED_1000_udpconnections=102050
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=470050
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2100
      - MAX_ALLOCS_ALLOWED_creating_10000_headers=100 # 5.2 improvement 10000
      - MAX_ALLOCS_ALLOWED_decode_1000_ws_frames=2000
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer=1000
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer_with_space=1000
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer=5010
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer_with_space=5010
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=75010
      - MAX_ALLOCS_ALLOWED_modifying_1000_circular_buffer_elements=50
      - MAX_ALLOCS_ALLOWED_modifying_byte_buffer_view=2010 # 5.2 improvement 4000
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4440
      - MAX_ALLOCS_ALLOWED_read_10000_chunks_from_file=200050
      - MAX_ALLOCS_ALLOWED_schedule_10000_tasks=90050
      - MAX_ALLOCS_ALLOWED_scheduling_10000_executions=20150
      - MAX_ALLOCS_ALLOWED_udp_1000_reqs_1_conn=16250
      - MAX_ALLOCS_ALLOWED_udp_1_reqs_1000_conn=200050
      - SANITIZER_ARG=--sanitize=thread
      - INTEGRATION_TESTS_ARG=-f tests_0[013-9]

  performance-test:
    image: swift-nio:16.04-5.2

  shell:
    image: swift-nio:16.04-5.2

  echo:
    image: swift-nio:16.04-5.2

  http:
    image: swift-nio:16.04-5.2
