version: "3"

services:

  runtime-setup:
    image: swift-nio:18.04-5.1
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.1.3"

  unit-tests:
    image: swift-nio:18.04-5.1

  integration-tests:
    image: swift-nio:18.04-5.1

  test:
    image: swift-nio:18.04-5.1
    environment:
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=30540
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=488050
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4440
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2100
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=75010
      - MAX_ALLOCS_ALLOWED_creating_10000_headers=10100
      - MAX_ALLOCS_ALLOWED_scheduling_10000_executions=20150
      - MAX_ALLOCS_ALLOWED_modifying_1000_circular_buffer_elements=50
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer=1010
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer_with_space=1010
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer=4010
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer_with_space=4010
      - MAX_ALLOCS_ALLOWED_decode_1000_ws_frames=1000
      - MAX_ALLOCS_ALLOWED_modifying_byte_buffer_view=6010
      - MAX_ALLOCS_ALLOWED_schedule_10000_tasks=90050
      - MAX_ALLOCS_ALLOWED_read_10000_chunks_from_file=210050

  performance-test:
    image: swift-nio:18.04-5.1

  shell:
    image: swift-nio:18.04-5.1

  echo:
    image: swift-nio:18.04-5.1

  http:
    image: swift-nio:18.04-5.1
