version: "3"

services:

  runtime-setup:
    image: swift-nio:20.04-5.6
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.6"

  unit-tests:
    image: swift-nio:20.04-5.6

  integration-tests:
    image: swift-nio:20.04-5.6

  documentation-check:
    image: swift-nio:20.04-5.6

  test:
    image: swift-nio:20.04-5.6
    environment:
      - MAX_ALLOCS_ALLOWED_10000000_asyncsequenceproducer=22
      - MAX_ALLOCS_ALLOWED_1000000_asyncwriter=1000050
      - MAX_ALLOCS_ALLOWED_1000_addHandlers=45050
      - MAX_ALLOCS_ALLOWED_1000_addHandlers_sync=39050
      - MAX_ALLOCS_ALLOWED_1000_addRemoveHandlers_handlercontext=8050
      - MAX_ALLOCS_ALLOWED_1000_addRemoveHandlers_handlername=8050
      - MAX_ALLOCS_ALLOWED_1000_addRemoveHandlers_handlertype=8050
      - MAX_ALLOCS_ALLOWED_1000_autoReadGetAndSet=18050
      - MAX_ALLOCS_ALLOWED_1000_autoReadGetAndSet_sync=0
      - MAX_ALLOCS_ALLOWED_1000_copying_bytebufferview_to_array=1050
      - MAX_ALLOCS_ALLOWED_1000_copying_circularbuffer_to_array=1050
      - MAX_ALLOCS_ALLOWED_1000_getHandlers=8050
      - MAX_ALLOCS_ALLOWED_1000_getHandlers_sync=36
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=26400
      - MAX_ALLOCS_ALLOWED_1000_rst_connections=146000
      - MAX_ALLOCS_ALLOWED_1000_tcpbootstraps=4050
      - MAX_ALLOCS_ALLOWED_1000_tcpconnections=151050
      - MAX_ALLOCS_ALLOWED_1000_udp_reqs=6050
      - MAX_ALLOCS_ALLOWED_1000_udpbootstraps=2050
      - MAX_ALLOCS_ALLOWED_1000_udpconnections=77050
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=398000
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2050
      - MAX_ALLOCS_ALLOWED_creating_10000_headers=0
      - MAX_ALLOCS_ALLOWED_decode_1000_ws_frames=2050
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer=3
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer_with_mask=2050
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer_with_space=3
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer_with_space_with_mask=2050
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer=3050
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer_with_mask=5050
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer_with_space=3050
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer_with_space_with_mask=5050
      - MAX_ALLOCS_ALLOWED_execute_hop_10000_tasks=0
      - MAX_ALLOCS_ALLOWED_future_erase_result=4050
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=53050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form=700050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace=700050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_long_string=700050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_short_string=700050
      - MAX_ALLOCS_ALLOWED_modifying_1000_circular_buffer_elements=0
      - MAX_ALLOCS_ALLOWED_modifying_byte_buffer_view=2050
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=339
      - MAX_ALLOCS_ALLOWED_read_10000_chunks_from_file=140050
      - MAX_ALLOCS_ALLOWED_schedule_10000_tasks=60100
      - MAX_ALLOCS_ALLOWED_schedule_and_run_10000_tasks=60050
      - MAX_ALLOCS_ALLOWED_scheduling_10000_executions=86
      - MAX_ALLOCS_ALLOWED_udp_1000_reqs_1_conn=6200
      - MAX_ALLOCS_ALLOWED_udp_1_reqs_1000_conn=161050
      - FORCE_TEST_DISCOVERY=--enable-test-discovery
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  performance-test:
    image: swift-nio:20.04-5.6

  shell:
    image: swift-nio:20.04-5.6

  echo:
    image: swift-nio:20.04-5.6

  http:
    image: swift-nio:20.04-5.6
